# Generated by Django 4.2 on 2025-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['udid', 'timestamp'], name='udid_authau_udid_b12b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredentialslog',
            index=models.Index(fields=['udid', 'timestamp'], name='udid_encryp_udid_750e34_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['device_fingerprint', 'created_at'], name='udid_udidau_device__cea4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['udid', 'created_at'], name='udid_udidau_udid_1e93f0_idx'),
        ),
        migrations.AddIndex(
            model_name='udidauthrequest',
            index=models.Index(fields=['temp_token', 'created_at'], name='udid_udidau_temp_to_cf3f95_idx'),
        ),
    ]
