# Generated by Django 4.2 on 2025-11-05 15:24
#
# NO-OP: 0001_initial.py fue regenerado el 2026-01-22 para reflejar el estado
# completo y actual de los modelos (incluye ya los 5 AddIndex que esta
# migracion creaba originalmente, con los mismos nombres). Ejecutar estas
# operaciones de nuevo sobre una base de datos nueva falla con "el indice ya
# existe" porque 0001 ya los creo. Se dejan las operaciones vacias -en vez de
# borrar el archivo- para no romper la cadena de dependencias que usan las
# migraciones posteriores (0003, 0004).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udid', '0001_initial'),
    ]

    operations = []
