# Generated by Django 4.2 on 2025-11-06 15:59
#
# NO-OP: 0001_initial.py fue regenerado el 2026-01-22 para reflejar el estado
# completo y actual de los modelos (incluye ya los CreateModel de APIKey,
# Plan y Tenant, sus AddField de FK y todos sus AddIndex, con los mismos
# nombres). Ejecutar estas operaciones de nuevo sobre una base de datos nueva
# falla con "la tabla/el indice ya existe" porque 0001 ya los creo. Se dejan
# las operaciones vacias -en vez de borrar el archivo- para no romper la
# cadena de dependencias que usa la migracion posterior (0004).

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udid', '0002_authauditlog_udid_authau_udid_b12b2d_idx_and_more'),
    ]

    operations = []
